import * as YAML from "yaml";
import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";
import { McpServerConfig, SecurityPolicy, ShieldConfig } from "../types/config";

/**
 * Generates agentgateway YAML configuration from parsed MCP server configs.
 */
export class GatewayConfigGenerator {
  private config: ShieldConfig;

  constructor(config: ShieldConfig) {
    this.config = config;
  }

  /**
   * Generate the complete agentgateway configuration.
   */
  generate(): string {
    const gatewayConfig = this.buildConfig();
    return YAML.stringify(gatewayConfig, { indent: 2, lineWidth: 120 });
  }

  /**
   * Generate and write config to file.
   */
  writeToFile(outputPath: string): void {
    const yaml = this.generate();
    const header = [
      "# yaml-language-server: $schema=https://agentgateway.dev/schema/config",
      "# Generated by mcp-shield — https://github.com/bcornish1797/mcp-shield",
      `# Generated at: ${new Date().toISOString()}`,
      `# Source: ${this.config.source}`,
      `# Servers: ${this.config.servers.map((s) => s.name).join(", ")}`,
      "",
    ].join("\n");

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, header + yaml, "utf-8");
  }

  /**
   * Generate JWT keypair for testing.
   */
  static generateTestKeys(outputDir: string): { publicKeyPath: string; privateKeyPath: string } {
    const { publicKey, privateKey } = crypto.generateKeyPairSync("ec", {
      namedCurve: "P-256",
      publicKeyEncoding: { type: "spki", format: "pem" },
      privateKeyEncoding: { type: "pkcs8", format: "pem" },
    });

    fs.mkdirSync(outputDir, { recursive: true });
    const pubPath = path.join(outputDir, "pub-key.pem");
    const privPath = path.join(outputDir, "priv-key.pem");

    fs.writeFileSync(pubPath, publicKey);
    fs.writeFileSync(privPath, privateKey);

    return { publicKeyPath: pubPath, privateKeyPath: privPath };
  }

  private buildConfig(): Record<string, unknown> {
    const routes = this.buildRoutes();

    return {
      binds: [
        {
          port: this.config.gateway.port,
          listeners: [{ routes }],
        },
      ],
    };
  }

  private buildRoutes(): Record<string, unknown>[] {
    const routes: Record<string, unknown>[] = [];

    // Main federated MCP endpoint
    routes.push({
      matches: [
        { path: { exact: "/mcp" } },
        { path: { exact: "/.well-known/oauth-protected-resource/mcp" } },
      ],
      policies: this.buildPolicies(),
      backends: [
        {
          mcp: {
            targets: this.config.servers.map((server) => this.buildTarget(server)),
          },
        },
      ],
    });

    // Per-server endpoints for granular access
    for (const server of this.config.servers) {
      routes.push({
        matches: [
          { path: { exact: `/mcp/${server.name}` } },
          { path: { exact: `/.well-known/oauth-protected-resource/mcp/${server.name}` } },
        ],
        policies: this.buildPolicies(),
        backends: [
          {
            mcp: {
              targets: [this.buildTarget(server)],
            },
          },
        ],
      });
    }

    return routes;
  }

  private buildTarget(server: McpServerConfig): Record<string, unknown> {
    const target: Record<string, unknown> = { name: server.name };

    if (server.transport === "stdio" && server.command) {
      target.stdio = {
        cmd: server.command,
        args: server.args || [],
        ...(server.env && Object.keys(server.env).length > 0 ? { env: server.env } : {}),
      };
    } else if (server.url) {
      target.sse = { host: server.url };
    }

    return target;
  }

  private buildPolicies(): Record<string, unknown> {
    const policies: Record<string, unknown> = {};

    // CORS policy
    const cors = this.config.security.cors || {
      allowOrigins: ["*"],
      allowHeaders: ["mcp-protocol-version", "content-type", "cache-control", "authorization"],
      exposeHeaders: ["Mcp-Session-Id"],
    };
    policies.cors = {
      allowOrigins: cors.allowOrigins,
      allowHeaders: cors.allowHeaders,
      exposeHeaders: cors.exposeHeaders,
    };

    // Authentication policy
    if (this.config.security.auth.mode !== "permissive") {
      policies.mcpAuthentication = this.buildAuthPolicy();
    }

    // Rate limiting
    if (this.config.security.rateLimit) {
      policies.rateLimit = {
        requests: this.config.security.rateLimit.requestsPerMinute,
        unit: "minute",
        ...(this.config.security.rateLimit.burstSize ? { burst: this.config.security.rateLimit.burstSize } : {}),
      };
    }

    return policies;
  }

  private buildAuthPolicy(): Record<string, unknown> {
    const auth = this.config.security.auth;
    const policy: Record<string, unknown> = {
      mode: auth.mode,
      issuer: auth.issuer || "mcp-shield",
      audiences: auth.audiences || ["mcp-shield-client"],
    };

    if (auth.jwksSource === "file" && auth.jwksPath) {
      policy.jwks = { file: auth.jwksPath };
    } else if (auth.jwksSource === "url" && auth.jwksPath) {
      policy.jwks = { url: auth.jwksPath };
    } else {
      // Default to generated test key
      policy.jwks = { file: "./keys/pub-key.pem" };
    }

    policy.resourceMetadata = {
      resource: `http://${this.config.gateway.host}:${this.config.gateway.port}/mcp`,
      scopesSupported: ["read:all", "write:all", "admin"],
      bearerMethodsSupported: ["header"],
    };

    return policy;
  }
}
